"""initial schema

Revision ID: 8a7d80830fdd
Revises: 
Create Date: 2026-04-15 16:15:13.070833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a7d80830fdd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_assignment_soldier_assignment', 'assignment_soldiers', ['assignment_id'], unique=False)
    op.create_index('ix_assignment_date', 'assignments', ['date'], unique=False)
    op.create_index('ix_hour_slot_soldier_slot', 'hour_slot_soldiers', ['hour_slot_id'], unique=False)
    op.create_index('ix_hour_slot_assignment', 'hour_slots', ['assignment_id'], unique=False)
    op.create_index('ix_soldier_email', 'soldiers', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_soldier_email', table_name='soldiers')
    op.drop_index('ix_hour_slot_assignment', table_name='hour_slots')
    op.drop_index('ix_hour_slot_soldier_slot', table_name='hour_slot_soldiers')
    op.drop_index('ix_assignment_date', table_name='assignments')
    op.drop_index('ix_assignment_soldier_assignment', table_name='assignment_soldiers')
    # ### end Alembic commands ###
